- src/robot_dart/control/pd_control.cpp
- src/robot_dart/control/robot_control.cpp
- src/robot_dart/control/robot_control.hpp
DART now supports mimic joints (v>=6.7). This PR introduces small changes in robot control to take into account that mimic joints should not be controlled..
> DART now supports mimic joints (v>=6.7)

- src/examples/cameras.cpp
- src/robot_dart/graphics/camera_osr.hpp
- src/robot_dart/graphics/pbuffer_manager.hpp
See #21 
This PR adds a different way to manage pbuffer used by the cameras. 
**This is still WIP.** 
It requires OSG>=3.6 (to have osgViewer::ViewerBase::setUseConfigureAffinity(bool flag) function), I will probably put this into a `#ifdef` to make it optional. 
Opinions, comments, and ideas are welcome.
> new camera management

- src/examples/meshes.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
Hi again @costashatz, 
Another very small pull request. We are using a new urdf with meshes and we noticed that the color (defined in the dae file) was not displayed in our visualisations. Changing `SHAPE_COLOR` to `MATERIAL_COLOR` solved our issues, without changing the colors of all the examples in robot_dart. 
Can this small changed be merged to master?
Best,
> change visuals of materials

- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
_set_base_pose_ transforms the pose of a robot's base. 
It expects a transformation of type Eigen::Isometry3d as input.
> Added set_base_pose function

- waf_tools/corrade.py
- waf_tools/magnum.py
Hi, 
I have a small, yet annoying, issue when trying to compile robot_dart with python3 (i.e., without python2 on my system). The issue is when we look for the config files of magnum and corrade, which have an encoding that seems to be causing problem, in python3, not python2.
Here is a small PR that fix it. I have tested it on OSX, Ubuntu, with Python2 and Python3.
> Robust magnum detection

- waf_tools/dart.py
On my mac, the libode was compiled in static (libode.a) but we were only checking for the .dynlib library.
It broke the compilation since Dart was actually compiled with ODE but we were not finding ODE.
> Fix compilation on mac with ODE collision

- ci/install_magnum.sh
- cmake/RobotDARTConfig.cmake.in
- docs/installation.md
- src/python/gui.cpp
- src/python/robot.cpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/base_graphics.hpp
- src/robot_dart/gui/magnum/camera_osr.cpp
- src/robot_dart/gui/magnum/camera_osr.hpp
- src/robot_dart/gui/magnum/glfw_application.cpp
- src/robot_dart/gui/magnum/glfw_application.hpp
- src/robot_dart/gui/magnum/gs/camera.cpp
- src/robot_dart/gui/magnum/gs/camera.hpp
- src/robot_dart/gui/magnum/windowless_gl_application.cpp
- src/robot_dart/gui/magnum/windowless_gl_application.hpp
- src/robot_dart/gui_data.hpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
- wscript
This PR makes a few minor fixes in the `GuiData` and adds the possibility of display 3D axes. Here's an example:
These changes require to use the `Magnum EigenIntegration` but this is harmless as we just need to do just one `-DWITH_EIGEN=ON` when building `magnum-integration`. With a small restructure, now it is possible to more easily add more debug drawings if needed in the future.
> Possibility of displaying 3D axes

- cmake/example/example.cpp
- src/examples/arm.cpp
- src/examples/dof_maps.cpp
- src/examples/hexapod.cpp
- src/python/robot.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
- src/tests/test_robot.cpp
This PR adds aliases for `actuator types` of DART which we call `control modes`. @jbmouret I was thinking which control modes to provide to the user and I ended up with the conclusion that we should not provide any position control (either kinematic or dynamics with torques) as this would interfere with the control API. The user can use the step by step API to make a PID controller (they need to add one line of code!) and with the new functions they can change the control modes per dof/joint in a DART-free way (only by strings).
> Actuator Types

- cmake/RobotDARTConfig.cmake.in
Apparently the version check does not work with old version of eigen (which defeats the purpose). This new detection uses the code from dart.
> Fix a detection problem with CMake and old versions of Eigen3

- src/python/robot.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
Add jacobian, mass matrix and other helpers in Robot. A few things to note:
- I have given the possibility of "cutting" a jacobian or a mass matrix to a view of only the DOFs of interest.
- Although this might be good for debugging or very specific purposes, you should not use these views to perform computations for control/estimation (if you do not know exactly what you are doing, you will most probably do everything wrong).
- You should do something like the following: `joint_torques = robot->vec_dof(robot->jacobian("my_end_effector").transpose()*end_effector_wrench);`.
> Add jacobian, mass matrix and other helpers in Robot

- src/examples/cameras.cpp
- src/robot_dart/gui/magnum/gs/camera.cpp
- src/robot_dart/gui/magnum/gs/camera.hpp
I implemented it in the "good old way" because the unbuntu that is on the official Talos dev dockers/PC (16.x) does not have the right boost version.
We might remove this in the future once everybody has a a recent boost.
> Make boost.process optional (but make it possible to record videos)

- src/python/robot.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
This PR makes the `robot.reset()` function better and makes sure that when we clone or initialize with a skeleton, we reset everything to get a clean robot structure.
> Robot reset

- src/examples/robot_pool.cpp
- src/examples/talos.cpp
- src/robot_dart/robot_pool.cpp
- src/robot_dart/robot_pool.hpp
This is useful when we use robot_dart in many threads and we want to avoid parsing new robots from scratch.
Fix #99
> Create a robot pool

- src/examples/cameras.cpp
- src/examples/talos.cpp
- src/python/simu.cpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/glfw_application.cpp
- src/robot_dart/gui/magnum/graphics.cpp
- src/robot_dart/gui/magnum/gs/camera.cpp
- src/robot_dart/gui/magnum/gs/camera.hpp
- src/robot_dart/gui/magnum/sensor/camera.cpp
- src/robot_dart/gui/magnum/windowless_gl_application.cpp
- src/robot_dart/gui/magnum/windowless_graphics.cpp
- src/robot_dart/gui_data.hpp
- src/robot_dart/robot_dart_simu.cpp
- src/robot_dart/robot_dart_simu.hpp
- src/robot_dart/scheduler.cpp
- src/robot_dart/scheduler.hpp
See #41 
- status bar
- text panel (top left)
Still a bug with the vertical position of the status bar when we resize the window when it is too wide.
> Define placeholders for text

- src/examples/iiwa.cpp
- src/python/utils.cpp
- src/robot_dart/gui/magnum/glfw_application.cpp
- src/robot_dart/gui/magnum/gs/camera.cpp
- src/robot_dart/robot_dart_simu.cpp
- src/robot_dart/scheduler.cpp
- src/robot_dart/scheduler.hpp
We were computing the real-time factor using the wall time instead of the iteration time. This means that if we were real-time but had one iteration slower than realtime, we could never catch up and reach a real-time factor of 1. Basically, to reach a real-time factor of 1, we needed many iterations faster than real time if we had been late in the past.
I switched to a real-time factor that corresponds to the iteration time, which corresponds better to what we want to know (I think).
By the way, if you log the iteration time, you will see that in graphics we often have iterations that last 14 ms (400 ms at the start), which do not come from the 'sync' mechanism (apparently). There is no problem in _plain.
> fix the real time factor + improve scheduler + improve status bar

- src/python/gui.cpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/glfw_application.cpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.cpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.hpp
- src/robot_dart/gui/magnum/resources/PhongMultiLight.frag
- src/robot_dart/gui/magnum/windowless_gl_application.cpp
We were having too much specularity in our scenes. This PR addresses this issue + makes a small fix for ill-formed materials. Now there is a parameter to tune how much specularity we want in our scene.
> Fix specularity

- src/examples/talos.cpp
- src/python/ci.py
- src/python/example.py
- src/python/gui.cpp
- src/python/simu.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/glfw_application.cpp
- src/robot_dart/gui/magnum/glfw_application.hpp
- src/robot_dart/gui/magnum/sensor/camera.cpp
- src/robot_dart/gui/magnum/windowless_gl_application.cpp
- src/robot_dart/gui/magnum/windowless_gl_application.hpp
- src/robot_dart/robot_dart_simu.cpp
- src/robot_dart/robot_dart_simu.hpp
- we also slightly alter (lighter) the color of the checkered floor
- example in talos.cpp
For now, I did not do the change for the sensor/camera.cpp as there is no graphics configuration here (it would require to add an argument to the constructor).
> Add the possibility to change the background color

- waf_tools/dart.py
- waf_tools/magnum_plugins.py
It seems that linking to the dependencies is not required with modern OS/linkers (that is, we link with Dart and Dart links with assimp on its own).
If we do it, this easily leads to inconsistencies if we do not find the same version (e.g dart uses assimp5 and we find assimp3). Also, this is useless code to maintain :)
> Remove the link to the dependencies (esp. assimp)

- src/examples/cameras.cpp
- src/examples/magnum_contexts.cpp
- src/python/gui.cpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/graphics.cpp
- src/robot_dart/gui/magnum/graphics.hpp
- src/robot_dart/gui/magnum/windowless_graphics.cpp
- src/robot_dart/gui/magnum/windowless_graphics.hpp
Now we can easily turn on/off text rendering. By default, no text is rendered in windowless graphics mode. This solves #120 ...
> Make text rendering a parameter

- src/python/gui.cpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/gs/light.cpp
- src/robot_dart/gui/magnum/gs/light.hpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.cpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.hpp
- src/robot_dart/gui/magnum/resources/PhongMultiLight.frag
Now lights can decide to not cast shadows. One of the default lights now does not cast a shadow (removing thus the double shadows that seem weird).
> Shadow per Light

- src/robot_dart/gui/magnum/base_application.cpp
This PR introduces a fix for parallel contexts (see https://github.com/mosra/magnum/pull/495); requires latest Magnum.
> [magnum]: fix for parallel contexts

- src/examples/cameras.cpp
- src/python/gui.cpp
- src/python/robot.cpp
- src/robot_dart/gui/base.hpp
- src/robot_dart/gui/helper.cpp
- src/robot_dart/gui/helper.hpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/base_graphics.hpp
- src/robot_dart/gui/magnum/gs/camera.cpp
- src/robot_dart/gui/magnum/gs/camera.hpp
- src/robot_dart/gui/magnum/gs/helper.cpp
- src/robot_dart/gui/magnum/gs/helper.hpp
- src/robot_dart/gui/magnum/sensor/camera.cpp
- src/robot_dart/gui/magnum/sensor/camera.hpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
~~In this pull request, I have added a function that calculates the intrinsic matrix of a camera from the perspective projection matrix.~~
http://ksimek.github.io/2013/06/03/calibrated_cameras_in_opengl/
This PR adds capabilities to the camera sensor in order to get the point cloud from the depth buffer.
> Add full RGB-D sensor capabilities

- ci/install_dart_latest.sh
- docs/installation.md
- Default build type of dependencies "release"
This is taken from CI and I argue that it's a good default for most users.
- Add missing "DWITH_STBTRUETYPEFONT=ON"
This was missing when building magnum plugins and prevented the build of graphical examples.
- Instruction to build the examples
> Updates installation instructions.

- src/examples/a1.cpp
- src/examples/pendulum.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
- src/tests/test_robot.cpp
This PR is removing `RobotDamage` completely. @Aneoshun @jbmouret is any of you using this? If not, I'll merge once the tests pass.
> Remove Damages

- src/python/simu.cpp
- src/robot_dart/robot_dart_simu.cpp
- src/robot_dart/robot_dart_simu.hpp
This PR fixes #136... The way to use this:
```
robot1:
category_mask: 1 << 1
robot2:
category_mask: 1 << 2
floor:
category_mask: 1 << 3
```
This sets robot1 as category with number 2, robot2 as category with number 4, and floor as category with number 8. Now we set:
```
robot1:
collision_mask: 4 | 8
robot2:
collision_mask: 4
floor:
collision_mask: 0
```
Collisions are ignored if `collision_mask & category_mask_of_other == 0`. In the above example, what will happen is that robot1 will collide with both robot2 and the floor, while robot2 will only collide with robot1.
Overall using the combinations of category and collision masks (per BodyNode), we can create a very complex collision ignorance systems.
> [BitmaskCollisionFilter]: improve with category and collision mask

- waf_tools/magnum.py
It mainly skip the check for OpenGL libs since this is a framework and Magnum already does its stuffs for this. I am not sure this works for older OS X version because it was working before without this fix. 
However, we do not have that many OS X users (except me).
> fix big_sur (osx 11.6) compilation

- src/python/robot.cpp
- src/robot_dart/robot.hpp
- src/robot_dart/sensor/sensor.cpp
- src/robot_dart/sensor/sensor.hpp
- waf_tools/magnum.py
When we split a skeleton, some sensors point to unavailable bodies (or the robot would have no access to the sensors on the detached skeleton).
This PR use the `_attached` boolean (which was already here) to be able detach a sensor explicitly (to avoid a segv when it was attached to something that does not exist anymore).
One idea is that it is up to the user to know what to do when a sensor is detached (e.g., replace with zero). So, the user should check that the sensor is attached when working with damage and querying sensors.
> Allow to "break" sensors

- robots/franka/franka.urdf
- src/examples/franka.cpp
This PR adds the `EE` frame that is automatically defined by Franka in libfranka_ros and used everywhere in libfranka.
> [robots]: Add EE frame in Franka

- waf_tools/dart.py
We automatically check this in waf..
> DART >=6.13 requires C++17

- cmake/RobotDARTConfig.cmake.in
- cmake/UthequeConfig.cmake.in
- wscript
This PR allows the cmake.in to handle multiple inclusion case (when a library depends on several libraries that depend on  utheque / robot_dart)
Without it and in case of multiple inclusion there is an error at the  add_library stage because it has already been done
> cmake.in multiple inclusion

- waf_tools/magnum.py
It appears that in recent versions of OSX, the GL headers are removed and not needed anymore. @jbmouret @Aneoshun  can you verify that this is working OK in your Mac PCs?
> In OSX do not search for GL headers

- src/robot_dart/utils.hpp
- waf_tools/boost.py
- waf_tools/corrade.py
- waf_tools/dart.py
- waf_tools/eigen.py
- waf_tools/magnum.py
- waf_tools/magnum_integration.py
- waf_tools/magnum_plugins.py
- waf_tools/pybind.py
- wscript
A few minor improvements:
- add `-fPIC`
- add a directory in dart.py to find dart
- add line number in ROBOT_DART_ASSERT
> minor improvements to wscript (-fPIC) and dart.py + add line number in assert

- src/python/robot.cpp
- src/robot_dart/robots/a1.cpp
- src/robot_dart/robots/a1.hpp
- src/robot_dart/robots/hexapod.hpp
- src/robot_dart/robots/icub.cpp
- src/robot_dart/robots/icub.hpp
- src/robot_dart/robots/talos.cpp
- src/robot_dart/robots/talos.hpp
- src/robot_dart/robots/tiago.cpp
Similar #182 but for all robots that need it..
> Add custom reset function to all robots that need it

- src/robot_dart/control/policy_control.hpp
This PR adds a warning message when DoFs are different from the policy output size.
During configure() if these values are different, the policy is not set to active but there is no message and this goes unnoticed by the user as the robot still moves (I'm not sure where these motor commands come from).
There is an assert on calculate() with the same condition, but it is not triggered if the policy was not flagged as active during configure().
> Add a warning message when policy is not set to active during configuration

- waf_tools/magnum.py
fix libdl detection for magnum in waf_tools when libdl.so is found but not libdl.so.2, that was breaking the build in ubuntu18.04 at least.
> waf_tools/magnum: fix libdl detection

- ci/install_dart_latest.sh
- ci/install_magnum.sh
- ci/install_packages.sh
- scripts/install_osx.sh
- scripts/install_ubuntu.sh
`set  -e` on all scripts for automatic exit on failed command
> Automatic exit of scripts on failure

- .clang-format
- .github/CONTRIBUTING.md
- README.md
Added a CONTRIBUTING.md file, updated the README, and included a .clang-format file.
> Contribution guideliness
