- docs/guide.md
- docs/installation.md
In addition to these commits, a few comments and questions on the guide.md:
- Robot Class / Controllers
- what is an active controller ?
- how to know which ID was given to a newly registered controller ?
- what does reinitialisation of a controller mean ?
- maybe we need to explain how weighting behaves and quickly say that it might be nice to have more than one controller (if it's true)
- Robot Class / Other functionalities
- I don't get what "attached damages" is
- RobotControl Class / Main methods / Constructor
- we now have method prototypes whereas we used to have usage examples; I prefer the former
- RobotDARTSimu Class / Robots: since `num_robots` retunrs a `size_t`, I think that we should enforce a limit on the number of robots
- RobotDARTSimu Class / Descriptors: what is …
> Proposed modifications for the documentation

- docs/installation.md
- waf_tools/dart.py
Do we have to link to OpenThreads on Linux as well?
> compilation on mac

- src/robot_dart/control/pd_control.cpp
- src/robot_dart/control/pd_control.hpp
Implemented a simpler version of the PD controller
> Implemented a simpler version of the PD controller

- src/robot_dart/control/pd_control.cpp
- src/robot_dart/control/pd_control.hpp
I tried to keep the code clean and create a good, flexible implementation. Sorry if there are some extra/missing white spaces :)
> Implemented different PD gains for each joint

- waf_tools/avx.py
- wscript
Fix for #14 ... We check if DART is compiled with native flags and enable/disable them accordingly..
> AVX check to reduce segfaults

- src/examples/hexapod.cpp
- src/examples/meshes.cpp
- src/robot_dart/graphics/graphics.hpp
Hi @costashatz,
This is a simple pull request to add the possibility to add a grid on the ground in the visualisation. 
I have added this grid in the `hexapod` example to show the result. 
Let me know what you think. 
Best,
> add function add_grid in graphics

- src/examples/magnum.cpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/camera_osr.cpp
- src/robot_dart/gui/magnum/glx_application.cpp
- src/robot_dart/gui/magnum/glx_application.hpp
- src/robot_dart/gui/magnum/graphics.hpp
- src/robot_dart/gui/magnum/gs/cube_map.cpp
- src/robot_dart/gui/magnum/gs/cube_map.hpp
- src/robot_dart/gui/magnum/gs/light.cpp
- src/robot_dart/gui/magnum/gs/light.hpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.cpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.hpp
- src/robot_dart/gui/magnum/gs/shadow_map.cpp
- src/robot_dart/gui/magnum/gs/shadow_map.hpp
- src/robot_dart/gui/magnum/resources/CubeMap.frag
- src/robot_dart/gui/magnum/resources/CubeMap.geom
- src/robot_dart/gui/magnum/resources/CubeMap.vert
- src/robot_dart/gui/magnum/resources/PhongMultiLight.frag
- src/robot_dart/gui/magnum/resources/PhongMultiLight.vert
- src/robot_dart/gui/magnum/resources/ShadowMap.frag
- src/robot_dart/gui/magnum/resources/ShadowMap.vert
- src/robot_dart/gui/magnum/resources/resources.conf
- src/robot_dart/gui/magnum/sdl2_application.cpp
- src/robot_dart/gui/magnum/sdl2_application.hpp
This PR adds shadows to the Magnum graphics. The functionality is there but there needs to be some cleaning..
Here's an example of a scene with 2 point-lights with shadows:
> Magnum shadows

- src/examples/cameras.cpp
- src/examples/transparent.cpp
- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/camera_osr.cpp
- src/robot_dart/gui/magnum/glfw_application.cpp
- src/robot_dart/gui/magnum/glfw_application.hpp
- src/robot_dart/gui/magnum/graphics.hpp
- src/robot_dart/gui/magnum/gs/camera.cpp
- src/robot_dart/gui/magnum/gs/create_compatibility_shader.hpp
- src/robot_dart/gui/magnum/gs/cube_map_color.cpp
- src/robot_dart/gui/magnum/gs/cube_map_color.hpp
- src/robot_dart/gui/magnum/gs/material.cpp
- src/robot_dart/gui/magnum/gs/material.hpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.cpp
- src/robot_dart/gui/magnum/gs/phong_multi_light.hpp
- src/robot_dart/gui/magnum/gs/shadow_map.cpp
- src/robot_dart/gui/magnum/gs/shadow_map.hpp
- src/robot_dart/gui/magnum/gs/shadow_map_color.cpp
- src/robot_dart/gui/magnum/gs/shadow_map_color.hpp
- src/robot_dart/gui/magnum/resources/CubeMap.geom
- src/robot_dart/gui/magnum/resources/CubeMap.vert
- src/robot_dart/gui/magnum/resources/CubeMapColor.frag
- src/robot_dart/gui/magnum/resources/PhongMultiLight.frag
- src/robot_dart/gui/magnum/resources/ShadowMap.vert
- src/robot_dart/gui/magnum/resources/ShadowMapColor.frag
- src/robot_dart/gui/magnum/resources/resources.conf
- src/robot_dart/gui/magnum/windowless_gl_application.cpp
- src/robot_dart/gui/magnum/windowless_gl_application.hpp
- wscript
My original code was not visualizing transparent objects properly. This PR fixes this and adds one additional feature of having colored shadows for transparent objects (at the moment shadows do not pass through the transparent objects, which would be cool but not important for robot_dart). Here's an example:
I will merge once I test a few things...
> Transparent objects and colored shadows

- wscript
@Aneoshun this should fix your issue about installing the library on Mac. Let me know if this is okay..
> Fix installation

- waf_tools/dart.py
This PR attempts to fix #46.. It is not perfect, but I think this is OK for now.
What the authors of DART did is insane! They have an optional dependency that they fuse inside the main dart library! Not a different one!
In any case, @dalinel  can you check that it solves your issue (#46)? I checked in the docker image that you sent me and it compiles (beware of `LD_LIBRARY_PATH`).
> Fix DART detection (with octomap)

- src/examples/arm.cpp
- src/examples/pendulum.cpp
- src/python/robot.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
This PR attempts to fix #39 ...
@jbmouret @dalinel @PedroDesRobots
> Robot helper functions

- src/python/simu.cpp
- src/robot_dart/robot_dart_simu.cpp
- src/robot_dart/robot_dart_simu.hpp
This PR attempts to partly address #48.. I did not do the custom collision checks and ray casting because we would need to define a structure for the results. Since we do not need it at the moment, I will handle this at the moment.
The collision filtering is done through a bitmask check.
> RobotDARTSimu helpers

- wscript
It does not work yet (RobotDARTSimu is not linked)
> working on #58 (separate build for examples)

- cmake/example/example.cpp
- src/examples/arm.cpp
- src/examples/pendulum.cpp
- src/python/example.py
- src/python/simu.cpp
- src/robot_dart/descriptor/base_descriptor.cpp
- src/robot_dart/descriptor/base_descriptor.hpp
- src/robot_dart/robot_dart_simu.hpp
Add descriptors to python bindings
> Add descriptors to python bindings

- src/examples/dof_maps.cpp
- src/python/robot.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
Αdd easy limits access and reset in Robot class (+ python fix)..
> Αdd easy limits access and reset in Robot class

- robots/icub/icub.urdf
- src/examples/icub.cpp
Play a bit with the iCub example so that it moves (a kind of squat)
> improve example of icub

- src/robot_dart/gui/magnum/base_application.cpp
In latest magnum master, some functionalities are deprecated. This PR uses the newest version of Magnum. Creating this PR to ping @jbmouret, @dalinel to update Magnum before I merge.
> [magnum]: remove deprecated functionality

- src/examples/robot_pool.cpp
- src/robot_dart/robot_pool.cpp
- src/robot_dart/robot_pool.hpp
In the current implementation of the robot pool there was a deadlock. This PR fixes it and makes a nicer reset method.
> Deadlock fix and nicer reset for robot pool

- src/examples/icub.cpp
- src/python/sensor.cpp
- src/robot_dart/sensor/force_torque.cpp
- src/robot_dart/sensor/force_torque.hpp
- src/robot_dart/sensor/imu.cpp
- src/robot_dart/sensor/imu.hpp
ForceTorque sensor stores and gives wrenches (in addition to force/torque vectors). One note: force/torque getters make copies now..
> ForceTorque sensor stores wrenches/IMU sensor improvement

- src/python/robot.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
- src/robot_dart/robot_dart_simu.cpp
- src/robot_dart/robot_dart_simu.hpp
This is meant to solve #116... I have exposed almost all contact parameters for each BodyNode, and made the floor as a robot so that we can alter its values using the same API.
> Friction/restitution parameters available, floor as a robot

- src/robot_dart/gui/magnum/base_application.cpp
- src/robot_dart/gui/magnum/base_application.hpp
- src/robot_dart/gui/magnum/drawables.hpp
- src/robot_dart/robot_dart_simu.cpp
Up until now, when we would remove a robot the GUI would break. This PR fixes that.
> Allow for removals of robots in GUI

- src/robot_dart/scheduler.cpp
- src/robot_dart/scheduler.hpp
> Fix real-time factor reporting

- src/examples/tutorial.cpp
- src/robot_dart/robot.cpp
> [robot]: fix base/body pose

- src/robot_dart/robots/talos.cpp
Real data from Talos correspond to the ```"parent_to_child"``` FT sensor direction
> changed FT direction to correspond to real Talos

- src/python/robot.cpp
- src/python/simu.cpp
- src/robot_dart/robot.cpp
- src/robot_dart/robot.hpp
- src/robot_dart/robot_dart_simu.cpp
- src/robot_dart/robot_dart_simu.hpp
> Never allow to overshoot if position limits are enforced

- paper/paper.bib
Address the invalid DOI found in https://github.com/openjournals/joss-reviews/issues/6771#issuecomment-2376961361
> Fix DART DOI
